In [1]:
import pandas as pd

# import matplotlib.pyplot as plt

import sklearn
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn_pandas import DataFrameMapper

from keras.utils import to_categorical

import numpy as np
import json



Using TensorFlow backend.


# Read the CSV and Perform Basic Data Cleaning

In [2]:
df = pd.read_csv("Resources/03_new_df.csv")
df.describe()

Opening     Theaters        Budget      Runtime  Genre_Action  \
count  1.907000e+03  1907.000000  1.907000e+03  1907.000000   1907.000000   
mean   2.792583e+07  2913.979549  6.206534e+07   110.750393      0.359203   
std    2.729695e+07   702.092481  5.495635e+07    18.674676      0.479893   
min    1.000198e+07   629.000000  0.000000e+00    26.000000      0.000000   
25%    1.339860e+07  2503.000000  2.400000e+07    97.000000      0.000000   
50%    1.896668e+07  2950.000000  4.600000e+07   108.000000      0.000000   
75%    3.053719e+07  3389.500000  8.000000e+07   122.000000      1.000000   
max    3.571150e+08  4662.000000  5.000000e+08   201.000000      1.000000   

       Genre_Adventure  Genre_Animation  Genre_Comedy  Genre_Crime  \
count      1907.000000      1907.000000   1907.000000  1907.000000   
mean          0.280545         0.093865      0.409544     0.149449   
std           0.449384         0.291717      0.491879     0.356624   
min           0.000000         0.000000      0.000000     0.000000   
25%           0.000000         0.000000      0.000000     0.000000   
50%           0.000000         0.000000      0.000000     0.000000   
75%           1.000000         0.000000      1.000000     0.000000   
max           1.000000         1.000000      1.000000     1.000000   

       Genre_Documentary  ...  Writer_Yvette Kaplan  Writer_Zach Helm  \
count        1907.000000  ...           1907.000000       1907.000000   
mean            0.004719  ...              0.000524          0.000524   
std             0.068554  ...              0.022899          0.022899   
min             0.000000  ...              0.000000          0.000000   
25%             0.000000  ...              0.000000          0.000000   
50%             0.000000  ...              0.000000          0.000000   
75%             0.000000  ...              0.000000          0.000000   
max             1.000000  ...              1.000000          1.000000   

       Writer_Zach Shields  Writer_Zack Snyder  Writer_Zack Stentz  \
count          1907.000000         1907.000000         1907.000000   
mean              0.000524            0.002622            0.001573   
std               0.022899            0.051151            0.039642   
min               0.000000            0.000000            0.000000   
25%               0.000000            0.000000            0.000000   
50%               0.000000            0.000000            0.000000   
75%               0.000000            0.000000            0.000000   
max               1.000000            1.000000            1.000000   

       Writer_Zak Penn  Writer_Zane Smith  Writer_Zeke Richardson  \
count      1907.000000        1907.000000             1907.000000   
mean          0.004719           0.000524                0.000524   
std           0.068554           0.022899                0.022899   
min           0.000000           0.000000                0.000000   
25%           0.000000           0.000000                0.000000   
50%           0.000000           0.000000                0.000000   
75%           0.000000           0.000000                0.000000   
max           1.000000           1.000000                1.000000   

       Writer_Álvaro Rodríguez  Writer_Éric Toledano  
count              1907.000000           1907.000000  
mean                  0.000524              0.000524  
std                   0.022899              0.022899  
min                   0.000000              0.000000  
25%                   0.000000              0.000000  
50%                   0.000000              0.000000  
75%                   0.000000              0.000000  
max                   1.000000              1.000000  

[8 rows x 16220 columns]

In [3]:
df.head()

Studio    Opening  Theaters        Date     Budget  Runtime Rating  \
0     BV  357115007      4662  2019-04-26  356000000    181.0  PG-13   
1     BV  257698183      4474  2018-04-27  300000000    149.0  PG-13   
2     BV  247966675      4134  2015-12-18  245000000    136.0  PG-13   
3     BV  220009584      4232  2017-12-15  200000000    152.0  PG-13   
4   Uni.  208806270      4274  2015-06-12  150000000    124.0  PG-13   

   Genre_Action  Genre_Adventure  Genre_Animation  ...  Writer_Yvette Kaplan  \
0             1                1                0  ...                     0   
1             1                1                0  ...                     0   
2             1                1                0  ...                     0   
3             1                1                0  ...                     0   
4             1                1                0  ...                     0   

   Writer_Zach Helm  Writer_Zach Shields  Writer_Zack Snyder  \
0                 0                    0                   0   
1                 0                    0                   0   
2                 0                    0                   0   
3                 0                    0                   0   
4                 0                    0                   0   

   Writer_Zack Stentz  Writer_Zak Penn  Writer_Zane Smith  \
0                   0                0                  0   
1                   0                0                  0   
2                   0                0                  0   
3                   0                0                  0   
4                   0                0                  0   

   Writer_Zeke Richardson  Writer_Álvaro Rodríguez  Writer_Éric Toledano  
0                       0                        0                     0  
1                       0                        0                     0  
2                       0                        0                     0  
3                       0                        0                     0  
4                       0                        0                     0  

[5 rows x 16223 columns]

# Change Date

In [43]:
date_column = df["Date"].str.split("-", n = 2, expand = True) 
year_col= date_column[0] 
month_col= date_column[1] 
day_col= date_column[2] 

In [ ]:
# one_hot_year = OneHotEncoder(dtype=np.int, categories="auto", sparse=False).fit_transform(year_col.values.reshape(-1,1))
# one_hot_year = pd.Series(list(one_hot_year))
# # Create DataFrame 
# new_year_df = pd.DataFrame(one_hot_year, columns=["Year"]) 

In [ ]:
# one_hot_month = OneHotEncoder(dtype=np.int, categories="auto", sparse=False).fit_transform(month_col.values.reshape(-1,1))
# one_hot_month = pd.Series(list(one_hot_month))
# new_month_df = pd.DataFrame(one_hot_month, columns=["Month"]) 

In [ ]:
# one_hot_day = OneHotEncoder(dtype=np.int, categories="auto", sparse=False).fit_transform(day_col.values.reshape(-1,1))
# one_hot_day = pd.Series(list(one_hot_day))
# new_day_df = pd.DataFrame(one_hot_day, columns=["Day"]) 

In [44]:
year_col.describe()

count     1907
unique      40
top       2012
freq        89
Name: 0, dtype: object

In [45]:
label_encoder = LabelEncoder()
label_encoder.fit(year_col)
encoded_year = label_encoder.transform(year_col)

In [46]:
encoded_year

array([39, 38, 35, ..., 26, 34, 32])

In [47]:
one_hot_year = to_categorical(encoded_year)
one_hot_year

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [48]:
one_hot_year.shape

(1907, 40)

In [49]:
one_hot_month = to_categorical(month_col)
one_hot_month

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [50]:
one_hot_month.shape

(1907, 13)

In [51]:
one_hot_day = to_categorical(day_col)
one_hot_day

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [52]:
one_hot_day.shape

(1907, 32)

In [53]:
year_df = pd.DataFrame(one_hot_year).add_prefix('Year_')

In [54]:
month_df = pd.DataFrame(one_hot_month).add_prefix('Month_')

In [55]:
day_df = pd.DataFrame(one_hot_day).add_prefix('Day_')

In [56]:
date_df = pd.concat([year_df, month_df, day_df], axis=1)
date_df.shape

(1907, 85)

In [57]:
df = df.drop(columns=["Date"])
df = pd.get_dummies(df)
df.head()

Opening  Theaters     Budget  Runtime  Genre_Action  Genre_Adventure  \
0  357115007      4662  356000000    181.0             1                1   
1  257698183      4474  300000000    149.0             1                1   
2  247966675      4134  245000000    136.0             1                1   
3  220009584      4232  200000000    152.0             1                1   
4  208806270      4274  150000000    124.0             1                1   

   Genre_Animation  Genre_Comedy  Genre_Crime  Genre_Documentary  ...  \
0                0             0            0                  0  ...   
1                0             0            0                  0  ...   
2                0             0            0                  0  ...   
3                0             0            0                  0  ...   
4                0             0            0                  0  ...   

   Studio_Uni.  Studio_W/Dim.  Studio_WB  Studio_WB (NL)  Studio_Wein.  \
0            0              0          0               0             0   
1            0              0          0               0             0   
2            0              0          0               0             0   
3            0              0          0               0             0   
4            1              0          0               0             0   

   Rating_G  Rating_NR  Rating_PG  Rating_PG-13  Rating_R  
0         0          0          0             1         0  
1         0          0          0             1         0  
2         0          0          0             1         0  
3         0          0          0             1         0  
4         0          0          0             1         0  

[5 rows x 16270 columns]

In [58]:
df = pd.concat([df, date_df], axis=1)
df.head()

Opening  Theaters     Budget  Runtime  Genre_Action  Genre_Adventure  \
0  357115007      4662  356000000    181.0             1                1   
1  257698183      4474  300000000    149.0             1                1   
2  247966675      4134  245000000    136.0             1                1   
3  220009584      4232  200000000    152.0             1                1   
4  208806270      4274  150000000    124.0             1                1   

   Genre_Animation  Genre_Comedy  Genre_Crime  Genre_Documentary  ...  Day_22  \
0                0             0            0                  0  ...     0.0   
1                0             0            0                  0  ...     0.0   
2                0             0            0                  0  ...     0.0   
3                0             0            0                  0  ...     0.0   
4                0             0            0                  0  ...     0.0   

   Day_23  Day_24  Day_25  Day_26  Day_27  Day_28  Day_29  Day_30  Day_31  
0     0.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0  
1     0.0     0.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0  
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0  
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0  
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0  

[5 rows x 16355 columns]

# Create a Train Test Split
Use `Opening` for the y values

In [59]:
target = df["Opening"]
data = df.drop("Opening", axis=1)
feature_names = data.columns
data.head()

Theaters     Budget  Runtime  Genre_Action  Genre_Adventure  \
0      4662  356000000    181.0             1                1   
1      4474  300000000    149.0             1                1   
2      4134  245000000    136.0             1                1   
3      4232  200000000    152.0             1                1   
4      4274  150000000    124.0             1                1   

   Genre_Animation  Genre_Comedy  Genre_Crime  Genre_Documentary  Genre_Drama  \
0                0             0            0                  0            0   
1                0             0            0                  0            0   
2                0             0            0                  0            0   
3                0             0            0                  0            0   
4                0             0            0                  0            0   

   ...  Day_22  Day_23  Day_24  Day_25  Day_26  Day_27  Day_28  Day_29  \
0  ...     0.0     0.0     0.0     0.0     1.0     0.0     0.0     0.0   
1  ...     0.0     0.0     0.0     0.0     0.0     1.0     0.0     0.0   
2  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   Day_30  Day_31  
0     0.0     0.0  
1     0.0     0.0  
2     0.0     0.0  
3     0.0     0.0  
4     0.0     0.0  

[5 rows x 16354 columns]

In [60]:
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [61]:
X_train.head()

Theaters     Budget  Runtime  Genre_Action  Genre_Adventure  \
1405      2968   30000000    105.0             0                0   
680       3400  160000000    123.0             1                1   
1105      3158   40000000    116.0             0                0   
925       3030  100000000     85.0             0                1   
478       2986   60000000     91.0             0                0   

      Genre_Animation  Genre_Comedy  Genre_Crime  Genre_Documentary  \
1405                0             1            0                  0   
680                 0             0            0                  0   
1105                0             1            0                  0   
925                 1             0            0                  0   
478                 0             0            0                  0   

      Genre_Drama  ...  Day_22  Day_23  Day_24  Day_25  Day_26  Day_27  \
1405            1  ...     0.0     0.0     0.0     0.0     0.0     0.0   
680             0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
1105            0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
925             0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
478             0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

      Day_28  Day_29  Day_30  Day_31  
1405     0.0     0.0     0.0     0.0  
680      0.0     0.0     0.0     0.0  
1105     0.0     0.0     1.0     0.0  
925      0.0     0.0     0.0     0.0  
478      0.0     0.0     0.0     0.0  

[5 rows x 16354 columns]

In [62]:
y_train.head()

1405    13540486
680     24166110
1105    16797385
925     19404492
478     30517109
Name: Opening, dtype: int64

# Pre-processing

Scale the data using the MinMaxScaler

In [72]:
X_minmax = MinMaxScaler().fit(X_train)
# y_minmax = MinMaxScaler().fit(y_train)

In [73]:
X_train_scaled = X_minmax.transform(X_train)
X_test_scaled = X_minmax.transform(X_test)
# y_train_minmax = y_minmax.transform(y_train)
# y_test_minmax = y_minmax.transform(y_test)

In [63]:
# X_mapper = DataFrameMapper([(['Theaters', 'Budget', 'Runtime'], MinMaxScaler())], 
#                           default=None).fit(X_train)

In [64]:
# X_train_scaled = X_mapper.transform(X_train)
# X_test_scaled = X_mapper.transform(X_test)

In [74]:
X_train_scaled.shape

(1430, 16354)

In [75]:
X_train_scaled

array([[0.56586366, 0.06      , 0.45142857, ..., 0.        , 0.        ,
        0.        ],
       [0.67657611, 0.32      , 0.55428571, ..., 0.        , 0.        ,
        0.        ],
       [0.61455664, 0.08      , 0.51428571, ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.21655561, 0.05      , 0.56571429, ..., 0.        , 0.        ,
        0.        ],
       [0.63172732, 0.034     , 0.34857143, ..., 0.        , 0.        ,
        0.        ],
       [0.65171707, 0.064     , 0.34857143, ..., 0.        , 0.        ,
        0.        ]])

In [76]:
y_train.shape

(1430,)

# Train the Support Vector Machine

In [77]:
from sklearn.svm import SVC 
model = SVC(kernel='linear')
model.fit(X_train_scaled, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [78]:
print(f"Training Data Score: {model.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {model.score(X_test_scaled, y_test)}")
# print('Test Acc: %.3f' % model.score(X_test, y_test))

Training Data Score: 1.0
Testing Data Score: 0.0


# Hyperparameter Tuning

Use `GridSearchCV` to tune the `C` and `gamma` parameters

In [ ]:
# Create the GridSearchCV model
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1, 5, 10, 50],
              'gamma': [0.0001, 0.0005, 0.001, 0.005]}
grid = GridSearchCV(model, param_grid, verbose=3)

In [ ]:
# Train the model with GridSearch
grid.fit(X_train_minmax, y_train)

In [ ]:
print(grid.best_params_)
print(grid.best_score_)

In [ ]:
grid.score(X_train_minmax, y_train)

In [ ]:
grid.score(X_test_minmax, y_test)

In [ ]:
predictions = grid.predict(X_test_minmax)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

# Random Forest

In [79]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf = rf.fit(X_train_scaled, y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [80]:
print(rf.score(X_train_scaled, y_train))
print(rf.score(X_test_scaled, y_test))

0.9951048951048951
0.0


In [ ]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

In [ ]:
param_grid2 = {'n_estimators': [250, 300, 350],
              'max_depth': [125, 150, 175]}
grid2 = GridSearchCV(rf, param_grid2, verbose=3)

In [ ]:
grid2.fit(X_train_minmax, y_train)

In [ ]:
print(grid2.best_params_)
print(grid2.best_score_)

In [ ]:
grid2.score(X_train_minmax, y_train)

In [ ]:
grid2.score(X_test_minmax, y_test)

In [ ]:
predictions2 = grid2.predict(X_test_minmax)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions2))