In [1]:
import pandas as pd

# import matplotlib.pyplot as plt

import sklearn
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn_pandas import DataFrameMapper

from keras.utils import to_categorical

import numpy as np
import json



Using TensorFlow backend.


# Read the CSV and Perform Basic Data Cleaning

In [2]:
df = pd.read_csv("Resources/03_new_df.csv")
df.describe()

Opening     Theaters       Movie ID        Budget      Runtime  \
count  1.907000e+03  1907.000000    1907.000000  1.907000e+03  1907.000000   
mean   2.792583e+07  2913.979549   84520.794442  6.206534e+07   110.750393   
std    2.729695e+07   702.092481  131170.037936  5.495635e+07    18.674676   
min    1.000198e+07   629.000000      12.000000  0.000000e+00    26.000000   
25%    1.339860e+07  2503.000000    7456.000000  2.400000e+07    97.000000   
50%    1.896668e+07  2950.000000   11820.000000  4.600000e+07   108.000000   
75%    3.053719e+07  3389.500000   88396.500000  8.000000e+07   122.000000   
max    3.571150e+08  4662.000000  533642.000000  5.000000e+08   201.000000   

       Genre_Action  Genre_Adventure  Genre_Animation  Genre_Comedy  \
count   1907.000000      1907.000000      1907.000000   1907.000000   
mean       0.359203         0.280545         0.093865      0.409544   
std        0.479893         0.449384         0.291717      0.491879   
min        0.000000         0.000000         0.000000      0.000000   
25%        0.000000         0.000000         0.000000      0.000000   
50%        0.000000         0.000000         0.000000      0.000000   
75%        1.000000         1.000000         0.000000      1.000000   
max        1.000000         1.000000         1.000000      1.000000   

       Genre_Crime  ...  Writer_Yvette Kaplan  Writer_Zach Helm  \
count  1907.000000  ...           1907.000000       1907.000000   
mean      0.149449  ...              0.000524          0.000524   
std       0.356624  ...              0.022899          0.022899   
min       0.000000  ...              0.000000          0.000000   
25%       0.000000  ...              0.000000          0.000000   
50%       0.000000  ...              0.000000          0.000000   
75%       0.000000  ...              0.000000          0.000000   
max       1.000000  ...              1.000000          1.000000   

       Writer_Zach Shields  Writer_Zack Snyder  Writer_Zack Stentz  \
count          1907.000000         1907.000000         1907.000000   
mean              0.000524            0.002622            0.001573   
std               0.022899            0.051151            0.039642   
min               0.000000            0.000000            0.000000   
25%               0.000000            0.000000            0.000000   
50%               0.000000            0.000000            0.000000   
75%               0.000000            0.000000            0.000000   
max               1.000000            1.000000            1.000000   

       Writer_Zak Penn  Writer_Zane Smith  Writer_Zeke Richardson  \
count      1907.000000        1907.000000             1907.000000   
mean          0.004719           0.000524                0.000524   
std           0.068554           0.022899                0.022899   
min           0.000000           0.000000                0.000000   
25%           0.000000           0.000000                0.000000   
50%           0.000000           0.000000                0.000000   
75%           0.000000           0.000000                0.000000   
max           1.000000           1.000000                1.000000   

       Writer_Álvaro Rodríguez  Writer_Éric Toledano  
count              1907.000000           1907.000000  
mean                  0.000524              0.000524  
std                   0.022899              0.022899  
min                   0.000000              0.000000  
25%                   0.000000              0.000000  
50%                   0.000000              0.000000  
75%                   0.000000              0.000000  
max                   1.000000              1.000000  

[8 rows x 16221 columns]

# Change Date

In [3]:
date_column = df["Date"].str.split("-", n = 2, expand = True) 
year_col= date_column[0] 
month_col= date_column[1] 
day_col= date_column[2] 

In [4]:
one_hot_year = OneHotEncoder(dtype=np.int, categories="auto", sparse=False).fit_transform(year_col.values.reshape(-1,1))
one_hot_year = pd.Series(list(one_hot_year))

In [ ]:
# label_encoder = LabelEncoder()
# label_encoder.fit(df['Year'])
# encoded_y = label_encoder.transform(df['Year'])

In [ ]:
# for label, original_class in zip(encoded_y, df['Year']):
#     print('Original Class: ' + str(original_class))
#     print('Encoded Label: ' + str(label))
#     print('-' * 12)

In [ ]:
# one_hot_year = to_categorical(encoded_y)
# import numpy as np
# one_hot_year = to_categorical(year_col)
# one_hot_year.shape
# len(one_hot_year)

In [5]:
# Create DataFrame 
new_year_df = pd.DataFrame(one_hot_year, columns=["Year"]) 

In [6]:
one_hot_month = OneHotEncoder(dtype=np.int, categories="auto", sparse=False).fit_transform(month_col.values.reshape(-1,1))
one_hot_month = pd.Series(list(one_hot_month))
new_month_df = pd.DataFrame(one_hot_month, columns=["Month"]) 

In [7]:
one_hot_day = OneHotEncoder(dtype=np.int, categories="auto", sparse=False).fit_transform(day_col.values.reshape(-1,1))
one_hot_day = pd.Series(list(one_hot_day))
new_day_df = pd.DataFrame(one_hot_day, columns=["Day"]) 

In [8]:
date_df = pd.concat([new_year_df, new_month_df, new_day_df], axis=1)
date_df.shape

(1907, 3)

In [9]:
date_df.head()

Year  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                  Month  \
0  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]   
1  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]   
4  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]   

                                                 Day  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...

In [10]:
df = df.drop(columns=["Date", "Movie ID", "Title", "Genres", "Directing", "Producing", "Writing"])
df = pd.get_dummies(df)
df.head()

Opening  Theaters     Budget  Runtime  Genre_Action  Genre_Adventure  \
0  357115007      4662  356000000    181.0             1                1   
1  257698183      4474  300000000    149.0             1                1   
2  247966675      4134  245000000    136.0             1                1   
3  220009584      4232  200000000    152.0             1                1   
4  208806270      4274  150000000    124.0             1                1   

   Genre_Animation  Genre_Comedy  Genre_Crime  Genre_Documentary  ...  \
0                0             0            0                  0  ...   
1                0             0            0                  0  ...   
2                0             0            0                  0  ...   
3                0             0            0                  0  ...   
4                0             0            0                  0  ...   

   Studio_Uni.  Studio_W/Dim.  Studio_WB  Studio_WB (NL)  Studio_Wein.  \
0            0              0          0               0             0   
1            0              0          0               0             0   
2            0              0          0               0             0   
3            0              0          0               0             0   
4            1              0          0               0             0   

   Rating_G  Rating_NR  Rating_PG  Rating_PG-13  Rating_R  
0         0          0          0             1         0  
1         0          0          0             1         0  
2         0          0          0             1         0  
3         0          0          0             1         0  
4         0          0          0             1         0  

[5 rows x 16270 columns]

In [11]:
df = pd.concat([df, date_df], axis=1)
df.head()

Opening  Theaters     Budget  Runtime  Genre_Action  Genre_Adventure  \
0  357115007      4662  356000000    181.0             1                1   
1  257698183      4474  300000000    149.0             1                1   
2  247966675      4134  245000000    136.0             1                1   
3  220009584      4232  200000000    152.0             1                1   
4  208806270      4274  150000000    124.0             1                1   

   Genre_Animation  Genre_Comedy  Genre_Crime  Genre_Documentary  ...  \
0                0             0            0                  0  ...   
1                0             0            0                  0  ...   
2                0             0            0                  0  ...   
3                0             0            0                  0  ...   
4                0             0            0                  0  ...   

   Studio_WB (NL)  Studio_Wein.  Rating_G  Rating_NR  Rating_PG  Rating_PG-13  \
0               0             0         0          0          0             1   
1               0             0         0          0          0             1   
2               0             0         0          0          0             1   
3               0             0         0          0          0             1   
4               0             0         0          0          0             1   

   Rating_R                                               Year  \
0         0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1         0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2         0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3         0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4         0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                  Month  \
0  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]   
1  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]   
4  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]   

                                                 Day  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...  

[5 rows x 16273 columns]

# Create a Train Test Split
Use `Opening` for the y values

In [12]:
target = df["Opening"]
data = df.drop("Opening", axis=1)
feature_names = data.columns
data.head()

Theaters     Budget  Runtime  Genre_Action  Genre_Adventure  \
0      4662  356000000    181.0             1                1   
1      4474  300000000    149.0             1                1   
2      4134  245000000    136.0             1                1   
3      4232  200000000    152.0             1                1   
4      4274  150000000    124.0             1                1   

   Genre_Animation  Genre_Comedy  Genre_Crime  Genre_Documentary  Genre_Drama  \
0                0             0            0                  0            0   
1                0             0            0                  0            0   
2                0             0            0                  0            0   
3                0             0            0                  0            0   
4                0             0            0                  0            0   

   ...  Studio_WB (NL)  Studio_Wein.  Rating_G  Rating_NR  Rating_PG  \
0  ...               0             0         0          0          0   
1  ...               0             0         0          0          0   
2  ...               0             0         0          0          0   
3  ...               0             0         0          0          0   
4  ...               0             0         0          0          0   

   Rating_PG-13  Rating_R                                               Year  \
0             1         0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1             1         0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2             1         0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3             1         0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4             1         0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                  Month  \
0  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]   
1  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]   
4  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]   

                                                 Day  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...  

[5 rows x 16272 columns]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [14]:
X_train.head()

Theaters     Budget  Runtime  Genre_Action  Genre_Adventure  \
1405      2968   30000000    105.0             0                0   
680       3400  160000000    123.0             1                1   
1105      3158   40000000    116.0             0                0   
925       3030  100000000     85.0             0                1   
478       2986   60000000     91.0             0                0   

      Genre_Animation  Genre_Comedy  Genre_Crime  Genre_Documentary  \
1405                0             1            0                  0   
680                 0             0            0                  0   
1105                0             1            0                  0   
925                 1             0            0                  0   
478                 0             0            0                  0   

      Genre_Drama  ...  Studio_WB (NL)  Studio_Wein.  Rating_G  Rating_NR  \
1405            1  ...               0             0         0          0   
680             0  ...               0             0         0          0   
1105            0  ...               0             0         0          0   
925             0  ...               0             0         1          0   
478             0  ...               0             0         0          0   

      Rating_PG  Rating_PG-13  Rating_R  \
1405          1             0         0   
680           0             1         0   
1105          0             0         1   
925           0             0         0   
478           0             0         1   

                                                   Year  \
1405  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
680   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1105  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
925   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
478   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                     Month  \
1405  [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]   
680   [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]   
1105  [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]   
925   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]   
478   [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]   

                                                    Day  
1405  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  
680   [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...  
1105  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
925   [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
478   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...  

[5 rows x 16272 columns]

# Pre-processing

Scale the data using the MinMaxScaler

In [ ]:
# X_minmax = MinMaxScaler().fit(X_train[['Theaters', 'Budget', 'Runtime']])
# y_minmax = MinMaxScaler().fit(y_train)

In [ ]:
# X_train_minmax = X_minmax.transform(X_train[['Theaters', 'Budget', 'Runtime']])
# X_test_minmax = X_minmax.transform(X_test[['Theaters', 'Budget', 'Runtime']])
# y_train_minmax = y_minmax.transform(y_train)
# y_test_minmax = y_minmax.transform(y_test)

In [15]:
X_mapper = DataFrameMapper([(['Theaters', 'Budget', 'Runtime'], MinMaxScaler())], 
                          default=None).fit(X_train)

In [17]:
X_train_scaled = X_mapper.transform(X_train)
X_test_scaled = X_mapper.transform(X_test)

In [22]:
X_train_scaled

array([[0.5658636596617119, 0.060000000000000005, 0.4514285714285714,
        ...,
        array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])],
       [0.6765761148129165, 0.32, 0.5542857142857143, ...,
        array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
        array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
        array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])],
       [0.6145566376217324, 0.08, 0.5142857142857142, ...,
        array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
        array([0, 0, 0, 0

# Train the Support Vector Machine

In [23]:
from sklearn.svm import SVC 
model = SVC(kernel='linear')
model.fit(X_train_scaled, y_train)

ValueError: setting an array element with a sequence.

In [ ]:
print(f"Training Data Score: {model.score(X_train_minmax, y_train)}")
print(f"Testing Data Score: {model.score(X_test_minmax, y_test)}")
# print('Test Acc: %.3f' % model.score(X_test, y_test))

# Hyperparameter Tuning

Use `GridSearchCV` to tune the `C` and `gamma` parameters

In [ ]:
# Create the GridSearchCV model
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1, 5, 10, 50],
              'gamma': [0.0001, 0.0005, 0.001, 0.005]}
grid = GridSearchCV(model, param_grid, verbose=3)

In [ ]:
# Train the model with GridSearch
grid.fit(X_train_minmax, y_train)

In [ ]:
print(grid.best_params_)
print(grid.best_score_)

In [ ]:
grid.score(X_train_minmax, y_train)

In [ ]:
grid.score(X_test_minmax, y_test)

In [ ]:
predictions = grid.predict(X_test_minmax)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

# Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf = rf.fit(X_train_minmax, y_train)
print(rf.score(X_train_minmax, y_train))
print(rf.score(X_test_minmax, y_test))

In [ ]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

In [ ]:
param_grid2 = {'n_estimators': [250, 300, 350],
              'max_depth': [125, 150, 175]}
grid2 = GridSearchCV(rf, param_grid2, verbose=3)

In [ ]:
grid2.fit(X_train_minmax, y_train)

In [ ]:
print(grid2.best_params_)
print(grid2.best_score_)

In [ ]:
grid2.score(X_train_minmax, y_train)

In [ ]:
grid2.score(X_test_minmax, y_test)

In [ ]:
predictions2 = grid2.predict(X_test_minmax)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions2))